### ISSUE TITLE
When a new registration is done, last logged-in partner Qs are displayed

### ISSUE THREAD

**Issue by yobnytech** [yobnytech/queueone_issues_tracker#24] opened 2020-03-07 02:16 UTC
When a new registration is done, last logged-in partner Qs are displayed

**Comment by yobnytech** [comment] 2020-03-14 14:04
Duplicate of #41

**Comment by qonelead** [comment] 2020-03-16 19:42
Close this as duplicate of #41

**Closed as completed** 2020-03-17 01:19 UTC
Labels: qone_partner_web_app, test and close
